# Generated by Django 2.2.5 on 2019-10-05 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(default=0, max_length=200, unique=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('description', models.TextField(blank=True)),
                ('model_number', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
