# Generated by Django 2.2.5 on 2019-10-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0004_auto_20191005_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default=0, max_length=200),
        ),
    ]
