# Generated by Django 2.2.5 on 2019-10-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0007_gallery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
        ),
    ]
