# Generated by Django 2.2.5 on 2019-10-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0009_remove_gallery_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
        ),
    ]
