# Generated by Django 2.2.5 on 2019-10-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0016_hero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
