# Generated by Django 2.2.5 on 2019-10-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0017_delete_hero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='Photo',
        ),
    ]
