# Generated by Django 2.2.5 on 2019-10-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0018_auto_20191006_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
