# Generated by Django 2.2.5 on 2019-10-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0020_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='Image',
        ),
    ]
