# Generated by Django 2.2.5 on 2019-10-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0022_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
