# Generated by Django 2.2.5 on 2019-10-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0029_productphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
    ]
