# Generated by Django 2.2.5 on 2019-10-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0031_auto_20191008_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, default='media/images/card-1.jpg', null=True, upload_to='media/'),
        ),
    ]
