# Generated by Django 2.2.5 on 2019-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0033_auto_20191008_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
