# Generated by Django 2.2.5 on 2019-10-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0035_auto_20191008_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, default='media/images/default.png', null=True, upload_to='media/images/'),
        ),
    ]
