# Generated by Django 2.2.5 on 2019-10-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0006_auto_20191005_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(db_index=True, default=0, max_length=200),
        ),
    ]
