# Generated by Django 2.2.5 on 2019-10-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0008_auto_20191005_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
    ]
