# Generated by Django 2.2.5 on 2019-10-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0010_gallery_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
