# Generated by Django 2.2.5 on 2019-10-06 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0011_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Maximum 250 characters.', max_length=250)),
                ('slug', models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', null=True, unique=True)),
                ('caption', models.TextField(blank=True, help_text='An optional summary.', max_length=250)),
                ('date', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('image', models.ImageField(help_text='Maximum resolution 800x600. Larger images will be resized.', upload_to='photos')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Run.Album')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=255, verbose_name='Reviewer name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Run.Photo', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
