# Generated by Django 2.2.5 on 2019-10-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0012_album_photo_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.RemoveField(
            model_name='review',
            name='picture',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
