# Generated by Django 2.2.5 on 2019-10-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0019_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
