# Generated by Django 2.2.5 on 2019-10-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0024_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
