# Generated by Django 2.2.5 on 2019-10-06 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0027_auto_20191006_2330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
    ]
