# Generated by Django 2.2.5 on 2019-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0032_auto_20191008_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='media/'),
        ),
    ]
